### ISSUE TITLE
Publish as NPM module

### ISSUE THREAD

**Issue by nt1m** [FirefoxUX/icons#13]
It would be nice if devtools could simply use icons from this repo.

Since devtools will be using a more NPM based workflow, I think it would be a good idea to pull assets directly from here.

/cc @jlaster @bgrins

**Comment by BojanKogoj** [comment]
Any update on this?

**Comment by bwinton** [comment]
Not yet. It's probably coming, but I don't have any timeline as to when.

**Comment by BojanKogoj** [comment]
Can we close this? Added description in #47

**Comment by aminalhazwani** [comment]
The current npm module is a bit clanky. I would prefer to clean that up before closing this issue.

**Comment by aminalhazwani** [comment]
https://www.npmjs.com/package/photon-icons
