### ISSUE TITLE
Generate iOS and Android icons

### ISSUE THREAD

**Issue by nt1m** [FirefoxUX/icons#26]
At SF, @brassy- and @aminalhazwani mentioned generating iOS and Android icons. Generating PNGs isn't very hard to do, however, I don't know the exact specification of these PNGs (size, shape, color, ...)

**Comment by nt1m** [comment]
This simple script generates an 16x16 png URL for the sidebar icon.

```js
var canvas = document.createElement("canvas");
var ctx = canvas.getContext("2d");
var url = "http://design.firefox.com/icons/icons/new/sidebar-16.svg";
var img = document.createElement("img");

img.onload = function() {
  ctx.drawImage(img,0,0,16,16);
  console.log(canvas.toDataURL())
}
img.src = url;
```

**Comment by aminalhazwani** [comment]
hey @nt1m, that is correct! we would need to generate `1x`, `2x` and `3x` PNGs for iOS and `mdpi`, `hdpi`, `xhpi`, `xxhdpi` and `xxxhpi` for Android. Lemme ask mobile designers and engineers for the specific specs and follow up with you! Just that you know I am currently working with @bwinton on the sidebar for downloading the icons, see [PR](https://github.com/bwinton/icons/pull/1).

**Comment by nt1m** [comment]
@bwinton might be interested in the script in comment 2.

**Comment by nt1m** [comment]
iOS specs: https://github.com/mozilla-mobile/firefox-ios/tree/13186294f11b9bfc3279f94d7497ffcf6691a7a8/Client/Assets/Images.xcassets/find_close.imageset

**Comment by aminalhazwani** [comment]
Android now also support SVGs https://developer.android.com/studio/write/vector-asset-studio.html#about

**Comment by nt1m** [comment]
@aminalhazwani Awesome! Not sure the Fennec team is already using them though.

**Comment by aminalhazwani** [comment]
@nt1m Fennec is 50/50/. Focus full SVG 😄

**Comment by aminalhazwani** [comment]
I gave a thought about this one as it seems to be the next step once we merge https://github.com/bwinton/icons/pull/5.

Before getting into the proposal I have a question. Do you think we should push to the repository the generated icons? Maybe is needed once we start figuring out how to build a npm package or similar packages for other platforms. Or maybe we first build the package and then pull the icons in the website out of the package. Anyway, food for though!

So we could upload the source SVGs to the repository with the following folder structure:
```
icons-source/
  /arrowhead-down
    arrowhead-down-12.svg
    arrowhead-down-16.svg
    arrowhead-down-24-ios.svg
    arrowhead-down-24-android.svg
```
and then generate:
```
icons/
  /arrowhead-down
    /android 
      drawable-hdpi/
        arrowhead-down.png
      drawable-mdpi/
        arrowhead-down.png
      drawable-xhdpi/
        arrowhead-down.png
      drawable-xxhdpi/
        arrowhead-down.png
      drawable-xxxhdpi/
        arrowhead-down.png
      arrowhead-down-24-android.svg
    /desktop
      arrowhead-down-12.svg
      arrowhead-down-16.svg
    /ios
      arrowhead-down.imagest/
        Contents.json
        arrowhead-down.png
        arrowhead-down-2x.png
        arrowhead-down-3x.png
      arrowhead-down-24-ios.svg
    /web
      arrowhead-down-12.svg
      arrowhead-down-16.svg
```
If you select only one platform you get one of these four zips

- arrowhead-down-android.zip
- arrowhead-down-ios.zip
- arrowhead-down-desktop.zip
- arrowhead-down-web.zip

with inside the content described above.

If you select multiple platforms you get a arrowhead.zip with inside the platforms folders and inside the platform folders the respective content as described above.

Few other considerations:
- consolidate icon name (hyphes, underscoper, prefixes, suffixes, platform, ...)
- loop in android engineers for file naming, folder structure, both PNGs and SVGs
- loop in ios engineers for file naming, folder structure, and for PDF icon format for iOS 11
- this work should also be used as ground work for the code packages for different platforms

**Comment by nt1m** [comment]
@aminalhazwani So there are 2 different things here:
1) Generating PNG assets within this repo
2) Providing a download button to download PNG assets: this can be done without having to generate PNGs in this repo. You can simply use the `<canvas>` API to convert SVGs to PNGs inside Firefox, and JSZip to zip them

I don't think 1) is worth it unless there's actually a plan of exporting this repo as a package for Firefox android/iOS to use.

**Comment by aminalhazwani** [comment]
@nt1m let's make a plan for either exporting this repo as a package or let's create a new repo :) @bwinton can you create the `photon-tokens` repo where we can start to store the material for the design tokens packages?

**Comment by nt1m** [comment]
@aminalhazwani

For Android/iOS, I'm not too familiar with developing on these platforms, so you may want to loop in some iOS/Android engineers about making an installable package.

As for devtools/desktop, once photon assets are available, we can export this repo as an npm package. Thoughts @captainbrosset ?

**Comment by aminalhazwani** [comment]
Ok, let's this issue and create two separate ones, one for Android and one for iOS. I will link this issue to both the new issues for reference, thanks!
