### ISSUE TITLE
bwinton fork: icon fill fallbacks to default in preview when selecteing a new icon with sidebar open

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/icons#28]
Step to replicate:

- click on an icon to open the download sidebar
- select icon fill dark
- click on another icon

![jul-07-2017 3-51-00 pm](https://user-images.githubusercontent.com/1721875/27960590-20ab6ed4-632c-11e7-9853-141513e6389d.gif)

**Comment by nt1m** [comment]
I think that's fixed by my PR: https://github.com/bwinton/icons/pull/2
