### ISSUE TITLE
Add new icons to icon sheet

### ISSUE THREAD

**Issue by AmyYLee** [FirefoxUX/icons#33]
- [x] [Accessibility Icon.svg.zip](https://github.com/FirefoxUX/icons/files/1225572/Accessibility.Icon.svg.zip)
- [x] [Report site icon](https://bug1373650.bmoattachments.org/attachment.cgi?id=8897214)
- [x] about:addons icons
- [x] about:preferences icons

**Comment by AmyYLee** [comment]
New photon style icon for accessibility

**Comment by nt1m** [comment]
Morphing this issue

**Comment by aminalhazwani** [comment]
Hi @AmyYLee I added a11y and report icon to the website! I find the report glyph to be a bit puffy compared to the other icons, maybe due to the unusual round shapes. Is there anything we can do there to optimize it? Thanks!

**Comment by aminalhazwani** [comment]
I marked about:preferences as done because they use the same icons of the browser menu.

**Comment by aminalhazwani** [comment]
Added also about:addons icons as well!

**Comment by nt1m** [comment]
@aminalhazwani Sorry for the confusion, I edited the first comment to include more icons. I think Bryan Bell is behind the report icon.

**Comment by aminalhazwani** [comment]
@nt1m no worries! Actually thank you very much for following up during our absence 😅
