### ISSUE TITLE
Search icon on different platforms use different directions

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/icons#36]
As reported [here](https://github.com/FirefoxUX/photon/issues/70) consider if we should highlight icons direction.

**Comment by brassy-** [comment]
How do we want to fix it? Having a search-right and search-left and leave the design system website to explain why so? Do we really need a duplicate icon if it's just a matter of mirroring it?

**Comment by nt1m** [comment]
How about calling the windows/linux version search.svg and the mac version search-macos.svg

**Comment by aminalhazwani** [comment]
I think it makes sense to differentiate icons with file name only when the icon is different. For example as we do for the share icon with `share-macos.svg` and `share-win.svg`. For icons that have a platform orientation we can document it under the iconography page in the design system website and if we think it is necessary to remark it here we could consider to display a message in the sidebar when users are soon to download an icon. We have some real estate there ☺️ What do you think?

**Comment by brassy-** [comment]
@aminalhazwani that's it's exactly my point. Orientation is something it can be solved with code/with the implementation. I like the idea of the remark in the sidebar.

**Comment by aminalhazwani** [comment]
Ok, I talked with Firefox front-end engineers and they would prefer to have separate files for different platforms so that they don't have to do the CSS transforms but they can use the template language to separate from win/macos

**Comment by aminalhazwani** [comment]
Moved to https://github.com/FirefoxUX/photon-icons/issues/13
