### ISSUE TITLE
Updated Home Icon

### ISSUE THREAD

**Issue by enxinas** [FirefoxUX/icons#41]
Hi everyone, newbie here. So I've been testing the Nightly build for some time now and over time, and I started to feel like the Home icon seems a little busy so I made a couple mockups.

Original:
![original](https://user-images.githubusercontent.com/32417703/31180273-0fff662a-a8d3-11e7-8c59-801d004a4a62.png)

V1
![v1 edit](https://user-images.githubusercontent.com/32417703/31180296-1f54ba08-a8d3-11e7-8771-015a18277b24.png)

V2
![v2 edit](https://user-images.githubusercontent.com/32417703/31180310-2739196c-a8d3-11e7-992e-e60135293444.png)

SVGs (Just rename it back to .svg)
[home-16-edit.svg.zip](https://github.com/FirefoxUX/icons/files/1356068/home-16-edit.svg.zip)
[home-16-edit2.svg.zip](https://github.com/FirefoxUX/icons/files/1359592/home-16-edit2.svg.zip)

**Comment by brassy-** [comment]
Hi @enxinas! Thank you for your contribution!

We're happy with the current home icon, so even if really appreciate the time you put into it, we're not going to move forward with this issue.

If you're interested, you're more then welcome to [try](http://design.firefox.com/icons/viewer/#exit) [out](http://design.firefox.com/icons/viewer/#list) [some](http://design.firefox.com/icons/viewer/#caption) [of](http://design.firefox.com/icons/viewer/#cast) [our](http://design.firefox.com/icons/viewer/#narrate%20fast) [outdated](http://design.firefox.com/icons/viewer/#narrate%20slow) [icons](http://design.firefox.com/icons/viewer/#narrate)!
