### ISSUE TITLE
Add multiple names as attributes to make icons more discoverable

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/icons#42]
For example let the menu icon be discoverable if a user types hamburger. Let the bookmark icon if a user types star. And so on ☺️

**Comment by aminalhazwani** [comment]
@bwinton does #59 fix this issue?

**Comment by bwinton** [comment]
It could, if someone goes in and adds the extra names to the tokens…

**Comment by aminalhazwani** [comment]
> It could, if someone goes in and adds the extra names to the tokens…

😂 I kinda feel that should be me

**Comment by aminalhazwani** [comment]
Moved to https://github.com/FirefoxUX/photon-icons/issues/15
