### ISSUE TITLE
Use tags instead of categories

### ISSUE THREAD

**Issue by nt1m** [FirefoxUX/icons#44]
@shorlander suggested this, and I think it's a good idea.

**Comment by aminalhazwani** [comment]
tell me more ☺️

**Comment by nt1m** [comment]
@aminalhazwani Icons could have multiple tags for easier identification. The search icon could be tagged with `extensions`, `navigation` since it's used in multiple places.

The arrows could have the `subview` tag they are used for panel subviews. It could also have the `control-center` tag since it's used in the control-center.

This way, if you search a specific tag, you can see all icons that are related to it.

**Comment by brassy-** [comment]
I think we discuss this idea with @bwinton already. Personally, I'd love and I think we really need to. 

@nt1m do you have any idea of how to implement this?

**Comment by aminalhazwani** [comment]
This is issue is probably a duplicate of #42 ☺️

**Comment by aminalhazwani** [comment]
We can close this thanks to this https://github.com/FirefoxUX/photon-icons
