### ISSUE TITLE
Lock icon

### ISSUE THREAD

**Issue by ryanfeeley** [FirefoxUX/icons#45]
One of the section of FxA is locked until users verify their email. Would love a lock icon.

**Comment by nt1m** [comment]
This one ? https://github.com/FirefoxUX/people/blob/gh-pages/shorlander/photon/Mockups/images-context-fill/secure-16.svg

**Comment by ryanfeeley** [comment]
Yes, but it's deprecated in the icon viewer. http://design.firefox.com/icons/viewer/#secure

**Comment by nt1m** [comment]
@ryanfeeley That's the new photon one. It hasn't been put inside the icon viewer yet.

@aminalhazwani Are there any plans to add that one ?

**Comment by aminalhazwani** [comment]
Yeah, we have a bunch of new icons that need to be uploaded. Will do it this week!

**Comment by aminalhazwani** [comment]
Forgot to cloe the issue, here you go https://design.firefox.com/icons/viewer/#lock
