### ISSUE TITLE
The 'Window 16' icon has a bottom-right outer corner radius of 2px, in contrast with all its other outer-radius being and the design guideline suggesting 3px

### ISSUE THREAD

**Issue by FatOrangutan** [FirefoxUX/icons#54]
Doesn't look like I can link an individual icon, so [here](http://design.firefox.com/icons/viewer/#window) is the search page for `window`.

**Comment by aminalhazwani** [comment]
Moved to https://github.com/FirefoxUX/photon-icons/issues/9
