### ISSUE TITLE
Create a default avatar for Firefox Accounts users everywhere

### ISSUE THREAD

**Issue by ryanfeeley** [FirefoxUX/icons#58]
*moved from Photon repo, original issue deleted*

![avatar](https://user-images.githubusercontent.com/68213/35572643-0df7dec0-05a3-11e8-8f19-e37b67aabae1.png)

The default profile pictures (a.k.a. avatars) for Firefox Accounts are now different on every version of Firefox (and different twice in desktop).

I would love to have a default profile picture that worked well on every platform, in a round or square crop.

This is a hard problem, as we need to be inclusive as possible.  Luckily some [great articles exist](https://uxdesign.cc/design-avatars-that-make-sense-and-be-more-inclusive-in-the-process-d4dd6a486ea6) for inspiration.

A bonus would be an avatar variation to indicate required actions (e.g. if the account requires verification).

As you can see, it does appear in different sizes. Anything in SVG will work fine.

**Comment by aminalhazwani** [comment]
Moved to https://github.com/FirefoxUX/photon-icons/issues/8
