### ISSUE TITLE
Review category separation and icon labels

### ISSUE THREAD

**Issue by nt1m** [FirefoxUX/icons#6]

**Comment by nt1m** [comment]
I think it would be best to separate categories as they are used in Firefox desktop, something like this:

General: all toolbar icons (this is probably too broad)
Page Action: all page action icons (copy url, email)
Control center: all permission/identity related icons
Activity Stream: all activity stream icons
Sync: all sync related icons (devices, sync, ...)

**Comment by brassy-** [comment]
hey @nt1m, 
I agree with you. I will even rename 'General' in 'Toolbar' so all the icons contains in the toolbar no matter the platform :) 

We're currently discussing this i.a. internally. I'd like to know a bit more why you think this rational (so having as much categories as much 'areas' we have in the firefox products) is the best :) 

Thanks!

**Comment by nt1m** [comment]
Engineers working on different teams will easily find what they need. If someone works on the control center, that person will know to look at the control center section, etc.

**Comment by aminalhazwani** [comment]
Moved to https://github.com/FirefoxUX/photon-icons/issues/16
