### ISSUE TITLE
Replace show password text with eyeballs

### ISSUE THREAD

**Issue by ryanfeeley** [FirefoxUX/icons#60]
FxA used to offer a Show Password toggle that stayed on until clicked again. For various reasons, we now only show the password when the button is held down.

This matches Microsoft's show password behaviour.

Is this okay for an eyeball password toggle? If not, can we get one?

<img width="373" alt="image" src="https://user-images.githubusercontent.com/68213/36117906-4b820c64-1009-11e8-9728-8d410bf1f350.png">

**Comment by changecourse** [comment]
I too have been wondering about this, and had created a slightly rounder version of the eyeball icon, for consideration...

<img width="1147" alt="screen shot 2018-02-12 at 2 10 56 pm" src="https://user-images.githubusercontent.com/6164801/36119890-a42d2b24-0ffe-11e8-92c6-4f026063958d.png">

**Comment by ryanfeeley** [comment]
We have a Photon icon!
![image](https://user-images.githubusercontent.com/68213/37209924-de4a20e4-2374-11e8-851e-c7e6788fa079.png)

SVGs attached: 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/68213/37210455-bf5422fa-2376-11e8-83e0-f83005f72641.png">

If possible, use colours from our Photon CSS (but I hard-coded secondary grey 90 and blue 50 in case that's not possible)
[password-mask-icons.zip](https://github.com/FirefoxUX/icons/files/1797061/password-mask-icons.zip)

**Comment by aminalhazwani** [comment]
Moved to https://github.com/FirefoxUX/photon-icons/issues/7
