### ISSUE TITLE
Add generic site favicon globe icon

### ISSUE THREAD

**Issue by johngruen** [FirefoxUX/icons#61]
Would be nice to have this icon on the photon site

<img width="343" alt="screen shot 2018-03-02 at 12 03 56 pm" src="https://user-images.githubusercontent.com/3323249/36919397-01f6eef4-1e12-11e8-98e2-68e0fab57776.png">

**Comment by aminalhazwani** [comment]
Moved to https://github.com/FirefoxUX/photon-icons/issues/6
