### ISSUE TITLE
Create a tablet icon

### ISSUE THREAD

**Issue by ryanfeeley** [FirefoxUX/icons#62]
Is there a tablet icon coming? Send to device knows and shows the difference.

https://design.firefox.com/icons/viewer/#device

**Comment by ryanfeeley** [comment]
Oh wait there is one, just not on the site.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/68213/37058990-2b98dba0-215a-11e8-8e21-d7300bae7c70.png">

**Comment by bwinton** [comment]
We should add it to the design-tokens module! :)

**Comment by ryanfeeley** [comment]
@bwinton Found it! [device-tablet.svg.zip](https://github.com/FirefoxUX/icons/files/1794288/device-tablet.svg.zip)

**Comment by ryanfeeley** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1443631
