### ISSUE TITLE
Detach repo

### ISSUE THREAD

**Issue by rugk** [FirefoxUX/icons#65]
Can you please detach this repo?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as it has been discontinued/is not maintained anymore and you…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. allows searching in this repo on GitHub and
5. it just looks much nicer

**Comment by aminalhazwani** [comment]
I agree, I think we should to that. Let me also create an issue for adding the list of contributors and contributing guidelines.

**Comment by brassy-** [comment]
It sounds quite right! @bwinton what do you think?

**Comment by nt1m** [comment]
I can simply delete my https://github.com/nt1m/firefox-svg-icons repository if you prefer.

**Comment by rugk** [comment]
That may be done too. Don't know if that also removes the link from here, though… :thinking:

**Comment by bwinton** [comment]
Let's give that a try, and see if it breaks the link, and if it doesn't, we can contact support.

**Comment by nt1m** [comment]
@bwinton deleted the original repository.

**Comment by rugk** [comment]
LGTM

I think this is solved.
