### ISSUE TITLE
Checkmark icon does not match checkmark in checkbox

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/icons#79]
The checkmark icon in our icons site does not match the checkmark in our checkboxes which makes them hard to replicate.

Checkmark icon:

<img width="106" alt="image" src="https://user-images.githubusercontent.com/473531/41542795-ca46366e-72e3-11e8-9e90-1f48c7875266.png">

Checkbox:

<img width="209" alt="image" src="https://user-images.githubusercontent.com/473531/41542826-d65babc8-72e3-11e8-853b-e42b82211d4d.png">

**Comment by aminalhazwani** [comment]
iirc it's by design 🙂 pinging shorlander for second confirmation.

**Comment by aminalhazwani** [comment]
Hello @sevaan, we talked with shorlander and we are going to use the checkmark that you can find on the icons website for the photon checkboxes. Following this up on the `photon-library` repo, thanks!
