### ISSUE TITLE
Use alphabetic sorting

### ISSUE THREAD

**Issue by nt1m** [FirefoxUX/icons#8]

**Comment by bwinton** [comment]
That's within categories, right?  Not just all the icons alphabetical?  😉

**Comment by nt1m** [comment]
Yep :D with the category names sorted alphabetically as well.

**Comment by bwinton** [comment]
I think this is done…  I'm not sure when or where, but could you test it and close it if it works?

**Comment by bwinton** [comment]
I'm pretty sure this works now.  :)
