### ISSUE TITLE
Missing icon: Accounts icon head

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/icons#82]
Was looking for this asset (about:preferences >> Account) and couldn't find it in our icons:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/473531/43022153-3bbe306c-8c34-11e8-998d-957c24ffe11b.png">

**Comment by nt1m** [comment]
Moved to https://github.com/FirefoxUX/photon-icons/issues/50
