### ISSUE TITLE
Can i use or edit or redesign "Photon Icons" (used icons in Firefox) for my commercials purposes ?

### ISSUE THREAD

**Issue by kada8** [FirefoxUX/icons#93]
Hi 
Can i use or edit or redesign "Photon Icons" (used icons in Firefox) for my commercials purposes and my business? 
this link :https://design.firefox.com/icons

**Comment by bwinton** [comment]
(Answered in [the other issue](https://github.com/FirefoxUX/photon-icons/issues/65).)
